name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y git zip unzip wget openjdk-17-jdk

      - name: Upgrade pip and install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython kivy numpy pytz arabic-reshaper python-bidi

      - name: Install Android Command-line Tools and Build Tools
        run: |
          # تحميل أدوات Android Command-line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d android-cmdline
          mkdir -p $HOME/Android/Sdk/cmdline-tools/latest
          mv android-cmdline/cmdline-tools/* $HOME/Android/Sdk/cmdline-tools/latest/
          
          # تعيين متغير البيئة لـ Android SDK
          export ANDROID_SDK_ROOT=$HOME/Android/Sdk
          
          # تثبيت Build Tools (الإصدار 31.0.0 يحتوي على AIDL)
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --install "build-tools;31.0.0"
          # تثبيت منصة Android المطلوبة (مثلاً android-31)
          yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --install "platforms;android-31"

      - name: Update PATH for Build Tools
        run: |
          echo "$HOME/Android/Sdk/build-tools/31.0.0" >> $GITHUB_PATH
          # التحقق من تثبيت AIDL
          $HOME/Android/Sdk/build-tools/31.0.0/aidl --version

      - name: Initialize Buildozer
        run: |
          buildozer init

      - name: Update buildozer.spec
        run: |
          # تعديل ملف buildozer.spec وفق إعدادات التطبيق
          sed -i 's/^title = .*/title = AstroApp/' buildozer.spec
          sed -i 's/^package\.name = .*/package.name = astroapp/' buildozer.spec
          sed -i 's/^package\.domain = .*/package.domain = org.example/' buildozer.spec
          sed -i 's/^version = .*/version = 0.1/' buildozer.spec
          sed -i 's/^requirements = .*/requirements = python3,kivy,numpy,pytz,arabic-reshaper,python-bidi/' buildozer.spec
          sed -i 's/^source\.include_exts = .*/source.include_exts = py,png,jpg,kv,ttf,otf,xml,json/' buildozer.spec
          sed -i 's/^# *source\.include_dirs = .*/source.include_dirs = planetimg,fonts/' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
