name: Build Kivy APK

on:
  push:
    branches:
      - main # أو اسم الفرع الرئيسي لديك

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip openjdk-11-jdk python3 python3-pip virtualenv android-sdk android-sdk-platform-tools android-tools-adb
          pip3 install cython==0.29.32 buildozer

      - name: Download and Extract Android SDK Command-line Tools
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          mkdir -p $ANDROID_HOME
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME
          # Find the extracted folder and move its content to latest
          extracted_folder=$(find $ANDROID_HOME -maxdepth 1 -type d -name "cmdline-tools*" | sort | tail -n 1)
          if [ -n "$extracted_folder" ]; then
            mv "$extracted_folder"/* "$ANDROID_HOME/cmdline-tools"
            mkdir "$ANDROID_HOME/cmdline-tools/latest"
            mv "$ANDROID_HOME/cmdline-tools/"* "$ANDROID_HOME/cmdline-tools/latest"
            rmdir "$ANDROID_HOME/cmdline-tools"
          else
            echo "Error: Extracted cmdline-tools folder not found."
            exit 1
          fi
          rm cmdline-tools.zip

      - name: Setup Android SDK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3:$PATH
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3:$PATH
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/app-debug.apk
