name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/build-tools/29.0.3:$PATH
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            tar \
            openjdk-8-jdk \
            python3-pip \
            python3-dev \
            build-essential \
            git \
            zip \
            unzip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libffi-dev \
            libssl-dev \
            libncurses5-dev \
            liblzma-dev \
            zlib1g-dev \
            libsqlite3-dev \
            libreadline-dev \
            wget

      - name: Download Android SDK Command Line Tools
        run: |
          mkdir -p ${{ github.workspace }}/android-sdk
          cd ${{ github.workspace }}/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/* cmdline-tools/latest/
          rm cmdline-tools.zip

      - name: Install Android SDK Packages
        run: |
          yes | ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=${{ github.workspace }}/android-sdk --licenses
          ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=${{ github.workspace }}/android-sdk "platform-tools" "platforms;android-29" "build-tools;29.0.3"

      - name: Upgrade pip and Install Buildozer
        run: |
          pip install --upgrade pip
          pip install cython==0.29.32
          pip install buildozer

      - name: Build APK with Buildozer
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-kivy-apk
          path: bin/*.apk
