name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-8-jdk \
            python3-pip \
            python3-dev \
            build-essential \
            git \
            zip \
            unzip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            libffi-dev \
            libssl-dev \
            libncurses5-dev \
            liblzma-dev \
            zlib1g-dev \
            libsqlite3-dev \
            libreadline-dev

      - name: Upgrade pip and Install Buildozer
        run: |
          pip install --upgrade pip
          pip install cython==0.29.32
          pip install buildozer

      - name: Build APK with Buildozer
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-kivy-apk
          path: bin/*.apk
