name: Build Kivy APK

on:
  push:
    branches:
      - main # أو اسم الفرع الرئيسي لديك

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip openjdk-11-jdk python3 python3-pip virtualenv android-sdk android-sdk-platform-tools android-tools-adb
          pip3 install cython==0.29.32 buildozer

      - name: Setup Android SDK
        run: |
          echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
          echo "y" | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: bin/app-debug.apk
